### ISSUE TITLE
Dask support

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#2578]
### What kind of feature would you like to request?

Additional function parameters / changed functionality / changed defaults?

### Please describe your wishes

Meta issue tracking scanpy functions without dask support

Related #921

First we should test things more generically:

- [x] add global `array_type` fixture to use in all tests for features below
  - #2595

@ivirshup came up with places where we should prioritize dask support:

- [x] `normalize_total`
  - seems to work: scverse/scanpy#2466
  - has tests: scverse/scanpy#1663
- [x] `log1p`, `normalize_per_cell`, `filter_cells`/`*_genes`:
  - [x] accept Dask arrays: scverse/scanpy#283
  - [x] Test that they are kept as Dask arrays throughout: scverse/scanpy#2814
- [x] `sc.pp.pca`: scverse/scanpy#2563 scverse/scanpy#3263
- [x] `sc.pp.calculate_qc_metrics` #3307
- `sc.pp.highly_variable_genes`:
  - [x] scverse/scanpy#2777
  - [x] scverse/scanpy#2807
  - [x] scverse/scanpy#2808
  - [ ] experimental “pearson_residuals” flavor
- [ ] `sc.tl.rank_genes_groups`
  - [x] depends on #2621
- [x] `sc.pp.subsample`/`sc.pp.sample`: so simple it has always been supported
- [x] Aggregate: https://flox.readthedocs.io/en/latest/ #3659
  - [x] CSC: #3872

Later:

- [x] scale scverse/scanpy#2942
- [ ] nearest-neighbors: https://github.com/dask/dask-ml/issues/982 may need to implement ourselves...
- [ ] umap: implement ourselves?
- [ ] metrics: depednent on squidpy decisions but should be dask-ifiable
- [ ] scrublet?

**Comment by mumichae** [comment]
For the highly_variable_genes dask support, are you also considering cases where the dask chunks are scipy sparse matrices?

**Comment by flying-sheep** [comment]
Not currently, but since the scope of that PR got reduced, it shouldn’t be too much work.

**Comment by jan-engelmann** [comment]
would be great to be able to use `sc.get.aggregate` with dask arrays!
