### ISSUE TITLE
Remove `sc.external`

### ISSUE THREAD

**Issue by flying-sheep** [scverse/scanpy#2717]
External has outlived its usefulness with the emergence of the scverse ecosystem, and should be removed.

^ This text should be expanded

# TODO

- [ ] Finalize methods to keep/ merge into main namespace
  - Currently: `scanorama`, `hashsolo`, `scrublet` or equivalent, maybe `bbknn`
- [ ] Make removal plan (probably deprecation message + maybe email to authors) for
  - [ ]  `harmony`
  - [ ] `dca`
  - [ ] `magic`
  - [ ] `phate`
  - [ ] `palantir`
  - [ ] `trimap`
  - [ ] `sam`
  - [ ] `phenograph`
  - [ ] `wishbone`
  - [ ] `sandbag`
  - [ ] `cyclone`
  - [ ] Export functionality for
    - [ ] `spring_project`
    - [ ] `cellbrowser`

**Comment by flying-sheep** [comment]
@Intron7 you said you have a sense which ones are still used.

Could you please weigh in here?

**Comment by flying-sheep** [comment]
TODO: create sub-issues for all tools and invite feedback by maintainers and users
- what’s still maintained (and therefore people should use the upstream one)
- what’s unmaintained but still used (and therefore we should take over)
